spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness-app-user
    username: postgres
    password: izyanupp
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect